Added our updated management client with the updated cloudcredential Client
igomez06/rancher pull request #6
Opened 2021-11-15 18:55 UTC by igomez06

2021-11-15 21:16 UTC, paynejacob requested changes
discussed this offline, we are going to take a different approach

2021-11-17 17:18 UTC, igomez06 commented
> discussed this offline, we are going to take a different approach

new changes are up now.

2021-11-17 19:45 UTC, paynejacob commented on tests/framework/extensions/cloudcredentials/config.go
> +const CloudCredentialType = "cloudCredential"
can we import this from the management client

2021-11-17 19:45 UTC, paynejacob commented on tests/framework/extensions/cloudcredentials/config.go
> +package cloudcredentials
nit: rename this file to `cloudcredentials.go`

2021-11-17 19:45 UTC, paynejacob approved these changes

2021-11-17 22:38 UTC, paynejacob approved these changes

2021-11-17 22:39 UTC, merged