Test framework user helpers
igomez06/rancher pull request #9
Opened 2021-11-22 04:08 UTC by igomez06

2021-11-22 16:19 UTC, paynejacob requested changes
Can you make this pr just the user framework changes.  This includes a lot more than the user helpers.

2021-11-22 16:22 UTC, igomez06 commented
> Can you make this pr just the user framework changes. This includes a lot more than the user helpers.

Once we get the other PR merged it will clean up this one. I branched off our the wait/watch branch.

2021-11-23 21:15 UTC, paynejacob requested changes

2021-11-23 21:15 UTC, paynejacob commented on tests/framework/extensions/users/users.go
> +	return rancherClient.Management.ProjectRoleTemplateBinding.Create(role)
add a wait to ensure the project namespace exists

2021-11-23 21:15 UTC, paynejacob commented on tests/framework/extensions/users/users.go
> +func RemoveProjectMember(rancherClient *rancher.Client, role *management.ProjectRoleTemplateBinding) error {
accept user in args here not bidng.

2021-11-23 21:15 UTC, paynejacob commented on tests/framework/extensions/users/users.go
> +func CreateUserWithRole(rancherClient *rancher.Client, user *management.User, role *management.GlobalRoleBinding) (*management.User, error) {
accept role and create the role binding for the user

2021-11-24 00:32 UTC, closed without merging